name: learn terraform workflow
on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Set up terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.4
      - name: Set up aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::506768526374:user/Aswini
          aws-region: eu-north-1

      - name: Initialize Terraform
        run: terraform init
      - name: Plan Terraform
        run: terraform plan
        env:
          TF_RENDER_API_KEY: ${{secrets.RENDER_API_KEY}}
          TF_RENDER_OWNER_ID: ${{secrets.RENDER_OWNER_ID}}
          TF_GHCR_USER_NAME: ${{secrets.GHCR_USER_NAME}}
          TF_GHCR_AUTH_TOKEN: ${{secrets.GHCR_AUTH_TOKEN}}
          TF_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          TF_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          TF_SECRET_KEY: ${{secrets.SECRET_KEY}}

#      - name: Wait for approval
#        uses: trstringer/manual-approval@v1.9.1
#        with:
#          approvers: {{secrets.GHCR_USER_NAME}}
#          minimum-approvals: 1
#          secret: ${{secrets.GITHUB_TOKEN}}

      - name : apply Terraform
        run : terraform apply -auto-approve
        env:
          TF_RENDER_API_KEY: ${{secrets.RENDER_API_KEY}}
          TF_RENDER_OWNER_ID: ${{secrets.RENDER_OWNER_ID}}
          TF_GHCR_USER_NAME: ${{secrets.GHCR_USER_NAME}}
          TF_GHCR_AUTH_TOKEN: ${{secrets.GHCR_AUTH_TOKEN}}
          TF_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          TF_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          TF_SECRET_KEY: ${{secrets.SECRET_KEY}}


